export { chatReducer, initialState } from "./chat-reducer";
export type {
  ChatAction,
  ChatStoreState,
  WorkspaceInfo,
  DmConversation,
  GroupDmConversation,
  GroupDmMember,
  PresenceEntry,
  ScrollTarget,
  ChannelPaginationState,
  ThreadPaginationState,
} from "./chat-reducer";

export type { AuthProvider, StorageProvider } from "./platform";
export {
  AuthError,
  ApiError,
  getErrorMessage,
  authorizedHeaders,
  authorizedRequest,
  createApiClient,
} from "./api";
export type { ApiClient } from "./api";

export { SocketManager } from "./socket";
export type {
  TypedSocket,
  SocketStatus,
  SocketSnapshot,
  SnapshotListener,
  TokenProvider,
} from "./socket";

export type { OperationDeps, ApiDeps } from "./operations";
export type { WorkspaceMember, ChannelMember, WorkspaceListItem, BrowseChannel, UserProfile } from "./operations";
export { normalizeChannel } from "./operations/normalize";
export {
  bootstrapWorkspace,
  loadChannelMessages,
  loadOlderMessages,
  loadNewerMessages,
  loadThreadMessages,
  loadOlderReplies,
  loadMoreReplies,
  toggleReaction,
  sendMessage,
  editMessage,
  deleteMessage,
  createDm,
  createGroupDm,
  handlePresenceSync,
  handlePresenceUpdate,
  handleUserStatusUpdated,
  handleNewMessageUnread,
  markChannelAsRead,
  markChannelAsUnread,
  handleHuddleSync,
  handleHuddleStarted,
  handleHuddleUpdated,
  handleHuddleEnded,
  setCurrentHuddleChannel,
  handleChannelMemberAdded,
  handleChannelMemberRemoved,
  createChannel,
  joinChannel,
  leaveChannel,
  browseChannels,
  updateChannelDescription,
  archiveChannel,
  unarchiveChannel,
  getInvite,
  acceptInvite,
  listWorkspaceMembers,
  updateMemberRole,
  removeMember,
  deleteWorkspace,
  checkAdmin,
  getStats,
  getActivity,
  getUsers,
  getAdminWorkspaces,
  impersonate,
  listChannelMembers,
  addChannelMember,
  removeChannelMember,
  listWorkspaces,
  createWorkspace,
  searchMessages,
  fetchStarredChannels,
  starChannelOp,
  unstarChannelOp,
  pinMessageOp,
  unpinMessageOp,
  fetchPinnedMessages,
  listBots,
  createBot,
  updateBot,
  deleteBot,
  regenerateBotToken,
  toggleBot,
  fetchChannelNotificationPrefs,
  setChannelNotificationPrefOp,
  getCurrentUser,
  updateCurrentUser,
  setUserStatus,
  clearUserStatus,
  fetchAllUnreads,
  markAllAsRead,
  shareMessageOp,
} from "./operations";
